id: P346ABE44
initial_creation_type: input
source_metadata:
  title: Rigdzin Gödem
  language: fr
  description: 'Texts by and about Rigdzin Gödem Ngödrup Gyaltsen (rig ''dzin rgod
    ldem dngos grub rgyal mtshan, 1337–1408), famed discoverer of the so-called Northern
    Treasures (byang gter) revelation:'
  volume:
    389e9efdb60444bcb6e6b2e3411047d6:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Aspiration Prayers
    5351800655f0476d84ef3836c9da7b5a:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    08101a396f8e4db89386f8a72c22d309:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    5e219bc2dca74668968637b2de10595a:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    4d76f6baa3be44d4a2c3f0cf9781a3bc:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    e7f289b16f9e4803b097824a1c03f369:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    414025df434b46d7aadcddd1bb3d1936:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    6d37b3924969483d8584cbe9b53e4fbc:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    3e78fb48dfa84891bb9c7497946f6bda:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
    c9d72a4b5e7344c4ba8590701ec4e08f:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Sādhanas
created_at: '2022-03-01T01:21:42.534513'
last_modified_at: '2022-03-01T01:21:42.534516'
